// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ArcaneConfig
    {
        public int id;
        public string name;
        public string des;
        public string icon;
        public int dmg;
        public int dmgType;
        public float radius;
        public float tickInterval;
        public float cd;
        public int runeCost;
        public int runeType;
        public int[] events;
        public int[] enemyEvents;
        public int[] bulletEvents;
    }

    [Serializable]
    public class ArcaneMeta
    {
        public int[] slot_ids;
    }

    [Serializable]
    public class ArcaneConfigData
    {
        public List<ArcaneConfig> items;
        public ArcaneMeta meta;
    }
}
