// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ArcaneConfig
    {
        [Serializable]
        public class LevelDesItem
        {
            public int level;
            public string des;
        }

        [Serializable]
        public class PassivesItem
        {
            public int level;
            public int id;
        }

        public int id;
        public string name;
        public string icon;
        public string des;
        public string upDes;
        public LevelDesItem[] levelDes;
        public int dmg;
        public int upDmg;
        public int dmgType;
        public int runeCost;
        public int runeType;
        public PassivesItem[] passives;
    }

    [Serializable]
    public class ArcaneConfigData
    {
        public List<ArcaneConfig> items;
    }
}
