// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class AttributeConfig
    {
        public int id;
        public string name;
        public string des;
        public int type;
        public int downLimit;
        public int upLimit;
        public int powerType;
    }

    [Serializable]
    public class AttributeConfigData
    {
        public List<AttributeConfig> items;
    }
}
