// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class BuffConfig
    {
        [Serializable]
        public class EvtDmgRateItem
        {
            public int type;
            public int rate;
        }

        [Serializable]
        public class SpecialEventItem
        {
            public int type;
            public int[] args;
        }

        public int id;
        public string name;
        public string icon;
        public string desc;
        public int overlap;
        public int probability;
        public int lastTime;
        public int jumpTime;
        public int eventEffect;
        public string position;
        public int type;
        public int dispel;
        public AttrEntry[] attribute;
        public EvtDmgRateItem[] evtDmgRate;
        public int[] evtDamage;
        public int[] evtWhenEnd;
        public SpecialEventItem[] specialEvent;
    }

    [Serializable]
    public class BuffConfigData
    {
        public List<BuffConfig> items;
    }
}
