// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class BulletStyleConfig
    {
        public int id;
        public string prefabPath;
    }

    [Serializable]
    public class BulletStyleConfigData
    {
        public List<BulletStyleConfig> items;
    }
}
