// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ChoiceGroupConfig
    {
        [Serializable]
        public class OptionsItem
        {
            public int id;
            public string text;
            public string description;
            public int effectId;
            public bool triggerBattle;
            public int goldReward;
        }

        public int id;
        public string title;
        public OptionsItem[] options;
    }

    [Serializable]
    public class ChoiceGroupConfigData
    {
        public List<ChoiceGroupConfig> items;
    }
}
