// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ChoiceGroupConfig
    {
        public int id;
        public string title;
        public int[] choices;
    }

    [Serializable]
    public class ChoiceGroupConfigData
    {
        public List<ChoiceGroupConfig> items;
    }
}
