// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ChoiceConfig
    {
        public int id;
        public string text;
        public string description;
        public int effectId;
        public bool triggerBattle;
        public int goldReward;
    }

    [Serializable]
    public class ChoiceConfigData
    {
        public List<ChoiceConfig> items;
    }
}
