// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class ConditionConfig
    {
        public int id;
        public string desc;
        public int type;
        public int p1;
        public int p2;
    }

    [Serializable]
    public class ConditionConfigData
    {
        public List<ConditionConfig> items;
    }
}
