// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class DialogueConfig
    {
        [Serializable]
        public class LinesItem
        {
            public string speaker;
            public int roleId;
            public int portraitSide;
            public string text;
        }

        public int id;
        public LinesItem[] lines;
    }

    [Serializable]
    public class DialogueConfigData
    {
        public List<DialogueConfig> items;
    }
}
