// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class EventEffectConfig
    {
        public int eventType;
        public float duration;
        public string target;
        public string prefabPath;
    }

    [Serializable]
    public class EventEffectConfigData
    {
        public List<EventEffectConfig> items;
    }
}
