// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class EventConfig
    {
        public int id;
        public int type;
        public string name;
        public string des;
        public int[] args;
    }

    [Serializable]
    public class EventConfigData
    {
        public List<EventConfig> items;
    }
}
