// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class EventEffectConfig
    {
        [Serializable]
        public class OffsetItem
        {
            public int x;
            public int y;
            public int z;
        }

        public int eventType;
        public OffsetItem[] offset;
        public string prefabPath;
    }

    [Serializable]
    public class EventEffectConfigData
    {
        public List<EventEffectConfig> items;
    }
}
