// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class EventShopConfig
    {
        [Serializable]
        public class ItemsItem
        {
            public int effectId;
            public int price;
            public int weight;
        }

        public int id;
        public string name;
        public int refreshCount;
        public ItemsItem[] items;
    }

    [Serializable]
    public class EventShopConfigData
    {
        public List<EventShopConfig> items;
    }
}
