// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class GlobalConfigData
    {
        // Global config is now handled via GameConsts.MetaConsts
    }
}
