// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class GlobalMeta
    {
        public int kill_count_for_boss;
        public float monster_spawn_interval;
    }

    [Serializable]
    public class GlobalConfigData
    {
        public GlobalMeta meta;
    }
}
