// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class HeroConfig
    {
        public int id;
        public string name;
        public string description;
        public int role;
        public int[] attack_skill_ids;
        public float skill_xp_interval;
        public int skill_xp_min;
        public int skill_xp_max;
        public AttrEntry[] attrs;
        public int[] charge_buff_ids;
    }

    [Serializable]
    public class HeroConfigData
    {
        public List<HeroConfig> items;
    }
}
