// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class LevelConfig
    {
        [Serializable]
        public class MonsterListItem
        {
            public int id;
            public int generate;
        }

        [Serializable]
        public class SuperMListItem
        {
            public int id;
            public int num;
            public int generate;
        }

        [Serializable]
        public class BossListItem
        {
            public int id;
            public int num;
        }

        public int id;
        public string name;
        public string des;
        public string bg;
        public int[] conditions;
        public int hard;
        public float spawn_interval;
        public int coinNormalKill;
        public int coinEliteKill;
        public int coinBossKill;
        public float coinSelfDestructRate;
        public MonsterListItem[] monsterList;
        public SuperMListItem[] superMList;
        public BossListItem[] bossList;
    }

    [Serializable]
    public class LevelConfigData
    {
        public List<LevelConfig> items;
    }
}
