// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class MonsterConfig
    {
        public int id;
        public string name;
        public int role;
        public int level;
        public bool is_boss;
        public bool is_elite;
        public int[] attack_skill_ids;
        public float attack_interval;
        public AttrEntry[] attrs;
    }

    [Serializable]
    public class MonsterConfigData
    {
        public List<MonsterConfig> items;
    }
}
