// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class PassiveEffectConfig
    {
        public int id;
        public string name;
        public string description;
        public string icon;
        public int effectType;
        public int targetAttrId;
        public int valueType;
        public float value;
        public bool stackable;
        public int maxStack;
    }

    [Serializable]
    public class PassiveEffectConfigData
    {
        public List<PassiveEffectConfig> items;
    }
}
