// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class PassiveEffectConfig
    {
        public int id;
        public string name;
        public string des;
        public string icon;
        public int color;
        public int level;
        public int[] passives;
        public int addGold;
        public int stackType;
        public int maxStack;
    }

    [Serializable]
    public class PassiveEffectConfigData
    {
        public List<PassiveEffectConfig> items;
    }
}
