// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class PassiveConfig
    {
        [Serializable]
        public class EventCondItem
        {
            public int id;
            public int[] args;
        }

        public int id;
        public string name;
        public string icon;
        public string des;
        public int[] eventTarget;
        public int[] eventRemove;
        public EventCondItem[] eventCond;
        public int[] events;
        public int[] skills;
    }

    [Serializable]
    public class PassiveConfigData
    {
        public List<PassiveConfig> items;
    }
}
