// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class RoleConfig
    {
        [Serializable]
        public class Sprite_setItem
        {
            public int slotType;
            public string spritePath;
        }

        public int id;
        public string name;
        public string prefabPath;
        public string animatorPath;
        public Sprite_setItem[] sprite_set;
        public string head;
    }

    [Serializable]
    public class RoleConfigData
    {
        public List<RoleConfig> items;
    }
}
