// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class RoleConfig
    {
        public int id;
        public string name;
        public string prefabPath;
        public string head;
    }

    [Serializable]
    public class RoleConfigData
    {
        public List<RoleConfig> items;
    }
}
