// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class SkillConfig
    {
        public int id;
        public int poolId;
        public int level;
        public string name;
        public string des;
        public string icon;
        public string category;
        public int dmg;
        public int dmgType;
        public float bulletSpeed;
        public float cd;
        public int bulletStyleId;
        public float attack_range;
        public int[] events;
        public int[] enemyEvents;
        public int[] bulletEvents;
    }

    [Serializable]
    public class SkillMeta
    {
        public int[] slot_ids;
    }

    [Serializable]
    public class SkillConfigData
    {
        public List<SkillConfig> items;
        public SkillMeta meta;
    }
}
