// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class SkillPoolConfig
    {
        public int id;
        public string name;
        public string[] desList;
        public string icon;
        public string dragHint;
    }

    [Serializable]
    public class SkillPoolConfigData
    {
        public List<SkillPoolConfig> items;
    }
}
