// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class SkillPoolConfig
    {
        [Serializable]
        public class LevelDesItem
        {
            public int level;
            public string des;
        }

        public int id;
        public string name;
        public string des;
        public string upDes;
        public LevelDesItem[] levelDes;
        public string icon;
        public string dragHint;
    }

    [Serializable]
    public class SkillPoolConfigData
    {
        public List<SkillPoolConfig> items;
    }
}
