// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class StoryNodeConfig
    {
        [Serializable]
        public class BossEventsItem
        {
            public int dialogueId;
            public int choiceGroupId;
        }

        [Serializable]
        public class NextNodesItem
        {
            public int nodeId;
            public int[] conditions;
        }

        public int id;
        public int collectionId;
        public string name;
        public string icon;
        public int type;
        public int levelId;
        public BossEventsItem[] bossEvents;
        public int dialogueId;
        public int choiceGroupId;
        public int shopId;
        public int defaultNextNodeId;
        public int failNodeId;
        public int endingType;
        public string endingCg;
        public int branchLineCount;
        public NextNodesItem[] nextNodes;
    }

    [Serializable]
    public class StoryNodeConfigData
    {
        public List<StoryNodeConfig> items;
    }
}
