// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;

namespace GeometryTD
{
    [Serializable]
    public class StoryCollectionConfig
    {
        public int id;
        public string name;
        public string description;
        public string icon;
        public int startNodeId;
        public int[] endingNodeIds;
    }

    [Serializable]
    public class StoryCollectionConfigData
    {
        public List<StoryCollectionConfig> items;
    }
}
