// ==========================================================
// AUTO-GENERATED by config_gen.py - DO NOT EDIT MANUALLY
// ==========================================================

using System;
using System.Collections.Generic;
using UnityEngine;

namespace GeometryTD
{
    public class ConfigManager : MonoBehaviour
    {
        public static ConfigManager Instance { get; private set; }

        // --- AUTO-GENERATED TABLE FIELDS ---
        public ConfigTable<ArcaneConfig, ArcaneMeta> arcaneTable;
        public ConfigTable<AttributeConfig> attributeTable;
        public ConfigTable<BuffConfig> buffTable;
        public ConfigTable<BulletEventConfig> bulletEventTable;
        public ConfigTable<BulletStyleConfig> bulletStyleTable;
        public ConfigTable<ChoiceGroupConfig> choiceGroupTable;
        public ConfigTable<ConditionConfig> conditionTable;
        public ConfigTable<DialogueConfig> dialogueTable;
        public ConfigTable<EventConfig> eventTable;
        public ConfigTable<EventEffectConfig> eventEffectTable;
        public ConfigTable<EventShopConfig> eventShopTable;
        public ConfigMeta<GlobalMeta> globalTable;
        public ConfigTable<HeroConfig, HeroMeta> heroTable;
        public ConfigTable<LevelConfig> levelTable;
        public ConfigTable<MonsterConfig, MonsterMeta> monsterTable;
        public ConfigTable<PassiveConfig> passiveTable;
        public ConfigTable<PassiveEffectConfig> passiveEffectTable;
        public ConfigTable<RoleConfig> roleTable;
        public ConfigTable<SkillConfig, SkillMeta> skillTable;
        public ConfigTable<SkillPoolConfig> skillPoolTable;
        public ConfigTable<StoryCollectionConfig> storyCollectionTable;
        public ConfigTable<StoryNodeConfig> storyNodeTable;

        // USER CODE START - Fields
        private Dictionary<int, GameObject> bulletPrefabCache;
        private Dictionary<int, GameObject> effectPrefabCache;
        private Dictionary<int, GameObject> rolePrefabCache;
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // USER CODE END - Fields

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
            DontDestroyOnLoad(gameObject);
            LoadAllConfigs();
        }

        private void LoadAllConfigs()
        {
            {
                var data = LoadConfig<ArcaneConfigData>("Configs/arcane_config");
                arcaneTable = new ConfigTable<ArcaneConfig, ArcaneMeta>();
                arcaneTable.Init(data.items, data.meta, c => c.id);
            }
            {
                var data = LoadConfig<AttributeConfigData>("Configs/attribute_config");
                attributeTable = new ConfigTable<AttributeConfig>();
                attributeTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<BuffConfigData>("Configs/buff_config");
                buffTable = new ConfigTable<BuffConfig>();
                buffTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<BulletEventConfigData>("Configs/bullet_event_config");
                bulletEventTable = new ConfigTable<BulletEventConfig>();
                bulletEventTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<BulletStyleConfigData>("Configs/bullet_style_config");
                bulletStyleTable = new ConfigTable<BulletStyleConfig>();
                bulletStyleTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<ChoiceGroupConfigData>("Configs/choice_group_config");
                choiceGroupTable = new ConfigTable<ChoiceGroupConfig>();
                choiceGroupTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<ConditionConfigData>("Configs/condition_config");
                conditionTable = new ConfigTable<ConditionConfig>();
                conditionTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<DialogueConfigData>("Configs/dialogue_config");
                dialogueTable = new ConfigTable<DialogueConfig>();
                dialogueTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<EventConfigData>("Configs/event_config");
                eventTable = new ConfigTable<EventConfig>();
                eventTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<EventEffectConfigData>("Configs/event_effect_config");
                eventEffectTable = new ConfigTable<EventEffectConfig>();
                eventEffectTable.Init(data.items, c => c.eventType);
            }
            {
                var data = LoadConfig<EventShopConfigData>("Configs/event_shop_config");
                eventShopTable = new ConfigTable<EventShopConfig>();
                eventShopTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<GlobalConfigData>("Configs/global_config");
                globalTable = new ConfigMeta<GlobalMeta>();
                globalTable.Init(data.meta);
            }
            {
                var data = LoadConfig<HeroConfigData>("Configs/hero_config");
                heroTable = new ConfigTable<HeroConfig, HeroMeta>();
                heroTable.Init(data.items, data.meta, c => c.id);
            }
            {
                var data = LoadConfig<LevelConfigData>("Configs/level_config");
                levelTable = new ConfigTable<LevelConfig>();
                levelTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<MonsterConfigData>("Configs/monster_config");
                monsterTable = new ConfigTable<MonsterConfig, MonsterMeta>();
                monsterTable.Init(data.items, data.meta, c => c.id);
            }
            {
                var data = LoadConfig<PassiveConfigData>("Configs/passive_config");
                passiveTable = new ConfigTable<PassiveConfig>();
                passiveTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<PassiveEffectConfigData>("Configs/passive_effect_config");
                passiveEffectTable = new ConfigTable<PassiveEffectConfig>();
                passiveEffectTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<RoleConfigData>("Configs/role_config");
                roleTable = new ConfigTable<RoleConfig>();
                roleTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<SkillConfigData>("Configs/skill_config");
                skillTable = new ConfigTable<SkillConfig, SkillMeta>();
                skillTable.Init(data.items, data.meta, c => c.id);
            }
            {
                var data = LoadConfig<SkillPoolConfigData>("Configs/skill_pool_config");
                skillPoolTable = new ConfigTable<SkillPoolConfig>();
                skillPoolTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<StoryCollectionConfigData>("Configs/story_collection_config");
                storyCollectionTable = new ConfigTable<StoryCollectionConfig>();
                storyCollectionTable.Init(data.items, c => c.id);
            }
            {
                var data = LoadConfig<StoryNodeConfigData>("Configs/story_node_config");
                storyNodeTable = new ConfigTable<StoryNodeConfig>();
                storyNodeTable.Init(data.items, c => c.id);
            }

            // USER CODE START - AfterLoad
            PreloadBulletPrefabs();
            PreloadEffectPrefabs();
            PreloadRolePrefabs();
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            // USER CODE END - AfterLoad
        }

        private T LoadConfig<T>(string path)
        {
            TextAsset textAsset = Resources.Load<TextAsset>(path);
            if (textAsset == null)
            {
                Debug.LogError("[ConfigManager] Failed to load: " + path);
                return default(T);
            }
            T config = JsonUtility.FromJson<T>(textAsset.text);
            if (config == null)
            {
                Debug.LogError("[ConfigManager] Failed to parse: " + path);
                return default(T);
            }
            return config;
        }

        // USER CODE START - CustomMethods
        public SkillConfig GetSkillConfigByPool(int poolId, int level)
        {
            return Cfg.Skill.Get(poolId * 100 + level);
        }

        public MonsterConfig GetBossConfig()
        {
            foreach (var m in Cfg.Monster.All)
            {
                if (m.is_boss) return m;
            }
            Debug.LogError("[ConfigManager] 未找到Boss配置");
            return null;
        }

        public List<MonsterConfig> GetNormalMonsterConfigs()
        {
            var normals = new List<MonsterConfig>();
            foreach (var m in Cfg.Monster.All)
            {
                if (!m.is_boss) normals.Add(m);
            }
            return normals;
        }

        public List<StoryNodeConfig> GetNodesByCollection(int collectionId)
        {
            var result = new List<StoryNodeConfig>();
            if (Cfg.StoryNode.All == null) return result;
            foreach (var node in Cfg.StoryNode.All)
            {
                if (node.collectionId == collectionId)
                    result.Add(node);
            }
            return result;
        }

        public GameObject GetBulletPrefab(int styleId)
        {
            if (bulletPrefabCache != null && bulletPrefabCache.TryGetValue(styleId, out var prefab))
                return prefab;
            return null;
        }

        public GameObject GetEffectPrefab(int eventType)
        {
            if (effectPrefabCache != null && effectPrefabCache.TryGetValue(eventType, out var prefab))
                return prefab;
            return null;
        }

        public GameObject GetRolePrefab(int roleId)
        {
            if (rolePrefabCache != null && rolePrefabCache.TryGetValue(roleId, out var prefab))
                return prefab;
            return null;
        }

        private void PreloadBulletPrefabs()
        {
            bulletPrefabCache = new Dictionary<int, GameObject>();
            if (Cfg.BulletStyle.All == null) return;
            foreach (var style in Cfg.BulletStyle.All)
            {
                if (string.IsNullOrEmpty(style.prefabPath)) continue;
                GameObject prefab = Resources.Load<GameObject>(style.prefabPath);
                if (prefab != null)
                    bulletPrefabCache[style.id] = prefab;
                else
                    Debug.LogWarning("[ConfigManager] 无法加载子弹Prefab: " + style.prefabPath + " (id=" + style.id + ")");
            }
        }

        private void PreloadEffectPrefabs()
        {
            effectPrefabCache = new Dictionary<int, GameObject>();
            if (Cfg.EventEffect.All == null) return;
            foreach (var effect in Cfg.EventEffect.All)
            {
                if (string.IsNullOrEmpty(effect.prefabPath)) continue;
                GameObject prefab = Resources.Load<GameObject>(effect.prefabPath);
                if (prefab != null)
                    effectPrefabCache[effect.eventType] = prefab;
                else
                    Debug.LogWarning("[ConfigManager] 无法加载特效Prefab: " + effect.prefabPath + " (eventType=" + effect.eventType + ")");
            }
        }

        private void PreloadRolePrefabs()
        {
            rolePrefabCache = new Dictionary<int, GameObject>();
            if (Cfg.Role.All == null) return;
            foreach (var role in Cfg.Role.All)
            {
                if (string.IsNullOrEmpty(role.prefabPath)) continue;
                GameObject prefab = GameHelper.LoadPrefab(role.prefabPath);
                if (prefab != null)
                    rolePrefabCache[role.id] = prefab;
                else
                    Debug.LogWarning("[ConfigManager] 无法加载角色Prefab: " + role.prefabPath + " (id=" + role.id + ")");
            }
        }

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // USER CODE END - CustomMethods
    }
}
